name: Test and Publish on Master Commit

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']  # Running tests on multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set RPC Token as Environment Variable
      run: |
        echo "RPC_TOKEN=${{ secrets.RPC_TOKEN }}" >> $GITHUB_ENV    

    - name: Install Tox
      run: |
        pip install tox

    - name: Run tests with Tox
      run: |
        tox -e py${{ matrix.python-version }}

  build_and_publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry for Test PyPI Authentication
      run: |
        poetry config pypi-token.test-pypi ${{ secrets.PYPI_API_TOKEN }} 

    - name: Build the package
      run: |
        poetry build -v

    - name: Publish the package to Test PyPI
      run: |
        poetry publish -r test-pypi -v